(function () {
    "use strict";
    const dictionary = {
        "Follow introductory courses with examples, practical tasks and knowledge checks. Complete the final test to earn a SecretCoder certificate.": "Проходите вводные курсы с примерами, практическими заданиями и проверкой знаний. Сдайте итоговый тест, чтобы получить сертификат SecretCoder.",
        "Start with introductory courses in web development, programming, data analysis and cloud basics.": "Начните с вводных курсов по веб-разработке, программированию, анализу данных и основам облачных технологий.",
        "Share your expertise with learners on SecretCoder. Apply to propose a course for the platform.": "Делитесь знаниями с учащимися SecretCoder. Подайте заявку и предложите курс для платформы.",
        "SecretCoder offers 12 introductory courses with lessons, practical tasks and knowledge checks. Materials are available in English and Russian. Complete all lessons and pass the final test to earn a certificate.": "SecretCoder предлагает 12 вводных курсов с уроками, практикой и проверкой знаний. Материалы доступны на английском и русском. Пройдите все уроки и сдайте итоговый тест, чтобы получить сертификат.",
        "Why choose SecretCoder courses?": "Почему стоит выбрать курсы SecretCoder?",
        "You can study at your own pace, resume saved progress and review lessons. Each course includes examples, practical tasks, a final test and a verifiable completion certificate.": "Учитесь в своём темпе, продолжайте с сохранённого места и повторяйте уроки. В каждом курсе есть примеры, практика, итоговый тест и сертификат со ссылкой для проверки.",
        "Register with your email address, open a course and select Start learning. Your enrolled courses appear in My Learning.": "Зарегистрируйтесь с помощью почты, откройте курс и нажмите «Начать обучение». Ваши курсы появятся в разделе «Моё обучение».",
        "3 lessons": "3 урока", "60 min": "60 мин", "View course": "О курсе", "View certificate": "Сертификат", "Course progress": "Прогресс курса", "Menu": "Меню",
        "Home": "Главная", "About": "О нас", "About Us": "О нас", "Courses": "Курсы", "All Courses": "Все курсы", "Pages": "Страницы", "Contact": "Контакты", "Contact Us": "Связаться с нами", "Login": "Войти", "Signup": "Регистрация", "Loading...": "Загрузка...",
        "Read More": "Подробнее", "Join Now": "Присоединиться", "Start For Free": "Начать бесплатно", "Welcome to Secret Coder": "Добро пожаловать в Secret Coder",
        "Best E-learning platform": "Платформа онлайн-обучения", "Learn Job ready skills from free online courses with certificates": "Освойте навыки для работы на бесплатных онлайн-курсах с сертификатами",
        "Explore a wide range of courses designed to enhance your expertise in technology, business, arts, and more. Start learning today!": "Выбирайте курсы по технологиям, бизнесу, искусству и другим направлениям. Начните учиться уже сегодня!",
        "Interactive Learning Experience": "Интерактивное обучение", "Engage with interactive lessons, quizzes, and projects. Experience hands-on learning that keeps you motivated and inspired.": "Учитесь с помощью интерактивных уроков, тестов и проектов. Практические задания помогут сохранить мотивацию и закрепить знания.",
        "Invest in your professional goals with Secret Coder": "Развивайтесь профессионально с Secret Coder",
        "Get unlimited access to over 90% of courses, Projects, Specializations, and Professional Certificates on Coursera, taught by top instructors.": "Получите неограниченный доступ к более чем 90% курсов, проектов, специализаций и профессиональных сертификатов Coursera от ведущих преподавателей.",
        "Learn anything": "Учитесь новому", "Explore any interest or trending topic, take prerequisites, and advance your skills": "Изучайте интересные и актуальные темы, осваивайте основы и совершенствуйте навыки",
        "Save money": "Экономьте", "Spend less money on your learning if you plan to take multiple courses this year": "Сократите расходы на обучение, если планируете пройти несколько курсов в этом году",
        "Flexible learning": "Гибкое обучение", "Learn at your own pace, move between multiple courses, or switch to a different course": "Учитесь в своём темпе, проходите несколько курсов или выбирайте новое направление",
        "Unlimited certificates": "Сертификат за каждый курс", "Earn a certificate for every learning program that you complete at no additional cost": "Получайте сертификаты за завершённые программы без дополнительной оплаты",
        "At Secret Coder, we believe in accessible, innovative learning experiences that adapt to your schedule and learning style. Join us in embracing the future of education and unlock your potential with our immersive online courses.": "В Secret Coder мы стремимся сделать современное обучение доступным и удобным для вашего расписания и стиля учёбы. Раскройте свой потенциал с нашими онлайн-курсами.",
        "Welcom to Secret Coder, your gateway to boundless learning opportunities. We're dedicated to democratizing education, offering a diverse range of courses taught by industry experts. Our mission is to empower learners worldwide, fostering a community-driven platform where knowledge knows no limits.": "Добро пожаловать в Secret Coder — мир возможностей для обучения. Мы делаем образование доступнее и предлагаем разнообразные курсы от экспертов. Наша цель — помогать людям по всему миру развиваться в сообществе, где знания не знают границ.",
        "Expert Instructors": "Опытные преподаватели", "Live Interactive Sessions": "Интерактивные занятия в прямом эфире", "Comprehensive Course Catalog": "Большой каталог курсов", "Community Engagement": "Общение в сообществе", "Personalized Learning Paths": "Индивидуальные траектории обучения", "Certification and Recognition": "Сертификаты и признание",
        "Explore Free Courses": "Откройте бесплатные курсы", "Start your online learning journey at Great Learning Academy for free with our short-term basic courses across various in-demand domains.": "Начните бесплатно учиться в Great Learning Academy на коротких базовых курсах по востребованным направлениям.",
        "Categories": "Категории", "categories": "категории", "Popular Topics to Explore": "Популярные направления", "Web Design": "Веб-дизайн", "Web Development": "Веб-разработка", "UI/UX Design": "UI/UX-дизайн", "Popular Courses": "Популярные курсы", "Explore new and trending free online courses": "Новые и популярные бесплатные онлайн-курсы",
        "FREE": "БЕСПЛАТНО", "Free": "Бесплатно", "PAID": "ПЛАТНО", "Enroll Now": "Записаться", "ENROLL NOW": "ЗАПИСАТЬСЯ", "Beginner": "Начальный", "Intermediate": "Средний",
        "HTML Course for Beginners": "HTML для начинающих", "Front End Development-CSS": "Фронтенд-разработка: CSS", "Introduction to JavaScript": "Введение в JavaScript", "Python Programming": "Программирование на Python", "SQL for Data Science": "SQL для анализа данных", "ChatGPT for Beginners": "ChatGPT для начинающих", "AWS for Beginners": "AWS для начинающих", "Microsoft Azure Essentials": "Основы Microsoft Azure", "Introduction to MS Excel": "Введение в Microsoft Excel", "Statistics For Data Science": "Статистика для анализа данных", "Java Programming": "Программирование на Java", "C for Beginners": "C для начинающих",
        "Become an Instructor": "Стать преподавателем", "Become An Instructor": "Стать преподавателем", "Start Teaching Today": "Начать преподавать", "Instructors from around the world teach millions of learners on Udemy. We provide the tools and skills to teach what you love.": "Преподаватели со всего мира обучают миллионы людей на Udemy. Мы предоставляем инструменты и навыки, чтобы вы могли преподавать любимый предмет.",
        "Frequently Asked Questions": "Частые вопросы", "What is the Secret Coder ?": "Что такое Secret Coder?",
        "The Secret Coder is an initiative taken by Secret Coder, where we offer 1000+ free online courses in cutting-edge technologies and have successfully enrolled a whopping 5 Million+ learners across all domains. Secret Coder covers courses on Data Science, Machine Learning, Artificial Intelligence, Cloud Computing, Software Development, Sales and Business Development, Digital Marketing, Big Data, and many more.": "Secret Coder предлагает более 1000 бесплатных онлайн-курсов по современным технологиям для более чем 5 миллионов учащихся. Среди направлений — анализ данных, машинное обучение, искусственный интеллект, облачные технологии, разработка ПО, продажи, бизнес, цифровой маркетинг и большие данные.",
        "Why should I choose Great Learning Academy for free courses with certificates ?": "Почему стоит выбрать бесплатные курсы с сертификатами Great Learning Academy?",
        "Great Learning Academy is an excellent choice for free courses with certificates because of the high quality of the learning content. The courses are well-crafted, offer a great learning experience, and are interactive and engaging, making them ideal for learners in identifying what works best for their career goals.": "Great Learning Academy предлагает качественные бесплатные курсы с сертификатами. Продуманные интерактивные материалы помогают учиться с интересом и выбирать навыки для достижения карьерных целей.",
        "How many free courses can I enroll in at the same time?": "На сколько бесплатных курсов можно записаться одновременно?", "You can simultaneously enroll in multiple courses at Secret Coder.": "В Secret Coder можно проходить несколько курсов одновременно.",
        "How can I enroll in these free online courses?": "Как записаться на бесплатные онлайн-курсы?", "You can click on the “Sign Up” button at the top-right of the page and register with your email address, or you can sign up using your Google Account.": "Нажмите «Регистрация» и создайте аккаунт с помощью электронной почты.",
        "What are the most popular free courses offered by Secret Coder ?": "Какие бесплатные курсы Secret Coder самые популярные?",
        "Secret Coder focuses on in-demand concepts and skills, where learners can develop industry-relevant knowledge in their chosen sector. It provides a wide range of courses in prestigious fields, assisting learners across the globe in achieving their professional goals.": "Secret Coder помогает освоить востребованные навыки и знания для выбранной профессии. Курсы по разным направлениям помогают людям по всему миру достигать профессиональных целей.",
        "Some of the most popular free courses offered by Secret Coder that are in high demand today include:": "Среди популярных бесплатных курсов Secret Coder:", "Free Data Science Courses": "Бесплатные курсы по анализу данных", "Free Artificial Intelligence Courses": "Бесплатные курсы по искусственному интеллекту", "Free Software Courses": "Бесплатные курсы по разработке ПО", "Free Cloud Computing Courses": "Бесплатные курсы по облачным технологиям",
        "Welcome to Secret Coder, where learning knows no boundaries. Our mission is to empower individuals worldwide through accessible and innovative education. Here's what sets us apart:": "Добро пожаловать в Secret Coder, где обучение не знает границ. Мы помогаем людям по всему миру развиваться благодаря доступному и современному образованию. Вот что нас отличает:",
        "Our Vision": "Наше видение", "At Secret Coder, we envision a world where learning is accessible to everyone, regardless of their location, background, or circumstances. We strive to break barriers and make education a transformative and inclusive experience for all.": "Мы хотим, чтобы обучение было доступно каждому независимо от места проживания, опыта и обстоятельств. Мы стремимся устранять барьеры и помогать всем менять свою жизнь с помощью образования.",
        "A Commitment to Excellence": "Стремление к качеству", "We are dedicated to providing top-quality education. Our team collaborates with industry experts and educators to curate courses that meet the highest standards, ensuring our learners receive valuable and up-to-date knowledge.": "Мы заботимся о качестве образования. Вместе с экспертами и преподавателями мы создаём курсы, которые дают полезные и актуальные знания.",
        "Empowering Learners": "Возможности для учащихся", "We believe in the transformative power of education. Secret Coder is designed to empower individuals to pursue their passions, advance their careers, and acquire new skills in a dynamic and supportive environment.": "Образование меняет жизнь. Secret Coder помогает развивать интересы, строить карьеру и осваивать новые навыки в дружелюбной среде.",
        "Innovation in Learning": "Современное обучение", "Embracing technology, we offer innovative learning methods and tools. From interactive modules to live sessions, we're committed to providing a cutting-edge learning experience that fosters engagement and knowledge retention.": "Мы используем современные методы и инструменты — от интерактивных модулей до занятий в прямом эфире. Они помогают учиться с интересом и лучше усваивать материал.",
        "Community-Centric Approach": "Сила сообщества", "Secret Coder is more than just courses; it's a vibrant community. We encourage collaboration, discussion, and knowledge sharing among learners, fostering an environment of growth and camaraderie.": "Secret Coder — это курсы и активное сообщество. Мы поддерживаем совместную работу, обсуждения и обмен знаниями, чтобы развиваться вместе.",
        "Diverse and Inclusive Education": "Образование для всех", "We celebrate diversity in perspectives, cultures, and ideas. Our diverse course offerings cater to various interests and skill levels, ensuring that everyone finds a learning path that resonates with them.": "Мы ценим разнообразие взглядов, культур и идей. Курсы для разных интересов и уровней подготовки помогут каждому найти своё направление.",
        "Continuous Improvement": "Постоянное развитие", "We are always evolving. Feedback from our learners helps us continually enhance our platform, ensuring it remains dynamic, responsive, and aligned with the evolving needs of our users.": "Мы постоянно развиваем платформу. Обратная связь учащихся помогает улучшать её и учитывать меняющиеся потребности пользователей.",
        "Thank you! for being a part of Secret Coder. Together, let's embark on a journey of lifelong learning and growth.": "Спасибо, что вы с Secret Coder! Давайте вместе учиться и развиваться на протяжении всей жизни.",
        "Quick Link": "Полезные ссылки", "Privacy Policy": "Политика конфиденциальности", "Terms & Condition": "Условия использования", "FAQs & Help": "Вопросы и помощь", "Subscribe to our Newsletter": "Подпишитесь на рассылку", "Subscribe now and join our growing community of learners committed to lifelong education!": "Подпишитесь на новости и присоединяйтесь к нашему сообществу учащихся!", "Subscribe": "Подписаться", ", All Right Reserved.": ", Все права защищены.", "© SecretCoder. Learn at your own pace.": "© SecretCoder. Учитесь в своём темпе.",
        "Get In Touch": "Свяжитесь с нами", "I'm happy to help! If you're looking for contact information or details about SecretCoder's online free courses website for e-learning, I don't have real-time browsing capabilities to access current websites or specific contact details.": "Есть вопросы об онлайн-курсах SecretCoder? Напишите нам с помощью формы ниже.", "Office": "Офис", "Mobile": "Телефон", "Email": "Электронная почта", "Your Name": "Ваше имя", "Your Email": "Ваша электронная почта", "Your email": "Ваша почта", "Subject": "Тема", "Message": "Сообщение", "Send Message": "Отправить", "Leave a message here": "Введите сообщение",
        "Email Address": "Электронная почта", "Password": "Пароль", "Forgot password?": "Забыли пароль?", "Don't have an account?": "Ещё нет аккаунта?", "Already have an account?": "Уже есть аккаунт?", "Username": "Имя пользователя",
        "My Learning": "Моё обучение", "Welcome,": "Добро пожаловать,", "learner": "учащийся", ". Keep building your skills.": ". Продолжайте развивать свои навыки.", "No courses yet": "Пока нет курсов", "Choose a course and start learning.": "Выберите курс и начните обучение.", "Explore courses": "Выбрать курс", "Start course": "Начать курс", "Continue learning": "Продолжить обучение", "Search courses": "Поиск курсов", "Search courses by title": "Поиск курсов по названию", "Sign out": "Выйти",
        "Apply As Instructor": "Подать заявку преподавателя", "Apply as Instructor": "Подать заявку преподавателя", "Welcome to SecretCoder - Where Knowledge Meets Innovation": "Добро пожаловать в SecretCoder — здесь знания встречаются с инновациями",
        "Are you passionate about sharing your expertise and making a real impact on learners worldwide? If so, we invite you to become an instructor on our dynamic e-learning platform! Join a community of educators dedicated to fostering a love for learning and empowering individuals to achieve their goals.": "Хотите делиться опытом и помогать людям по всему миру? Станьте преподавателем на нашей платформе! Присоединяйтесь к сообществу, которое вдохновляет учиться и достигать целей.",
        "Why Choose SecretCoder as Your Teaching Hub?": "Почему стоит преподавать в SecretCoder?", "Global Reach, Local Impact :": "Международная аудитория:", "Reach a diverse audience from all corners of the globe while making a meaningful difference in individual lives.": "Обучайте людей из разных стран и помогайте каждому менять свою жизнь.",
        "Cutting-Edge Technology :": "Современные технологии:", "Leverage our state-of-the-art e-learning infrastructure, ensuring a seamless and engaging learning experience for both you and your students.": "Используйте современные инструменты онлайн-обучения, удобные и для преподавателя, и для учащихся.",
        "Flexible Teaching Opportunities :": "Гибкий график преподавания:", "Create and manage your courses on a schedule that suits your lifestyle, allowing you to balance your professional and personal commitments.": "Создавайте и ведите курсы в удобное время, совмещая работу и личные дела.",
        "Competitive Compensation :": "Достойное вознаграждение:", "Benefit from a transparent and rewarding compensation structure that recognizes your expertise and commitment to education.": "Прозрачная система вознаграждения учитывает ваши знания и вклад в образование.",
        "How It Works": "Как это работает", "Your Journey to Becoming an Instructor": "Ваш путь к преподаванию", "Application Process": "Подача заявки", "Submit your application and provide details about your expertise, teaching philosophy, and the courses you want to offer.": "Подайте заявку, расскажите о своём опыте, подходе к обучению и курсах, которые хотите вести.",
        "Content Creation": "Создание материалов", "Develop high-quality course content with the support of our instructional design team, ensuring your materials are engaging and effective.": "Создавайте качественные учебные материалы с поддержкой нашей методической команды.",
        "Go Live": "Запуск курса", "Once approved, your courses go live on our platform, and learners from around the world can enroll and benefit from your knowledge.": "После одобрения курсы появятся на платформе, и учащиеся со всего мира смогут записаться.",
        "Engage and Grow": "Общение и развитие", "Interact with your students through discussion forums, live Q&A sessions, and feedback mechanisms, fostering a supportive learning community.": "Общайтесь с учащимися на форумах, отвечайте на вопросы в прямом эфире и собирайте обратную связь.",
        "What We Look for in Our Instructors": "Что мы ценим в преподавателях", "Passion for Teaching :": "Любовь к преподаванию:", "A genuine enthusiasm for sharing knowledge and facilitating the learning journey for others.": "Желание делиться знаниями и помогать другим учиться.", "Expertise in Your Field :": "Знание своего предмета:", "Demonstrated expertise in your subject matter, backed by relevant qualifications and experience.": "Подтверждённые знания, квалификация и опыт в выбранной области.",
        "Communication Skills :": "Навыки общения:", "Clear and effective communication to convey complex concepts and engage learners of various backgrounds.": "Умение понятно объяснять сложные темы учащимся с разным опытом.", "Innovation :": "Открытость новому:", "Willingness to embrace innovative teaching methods and technologies to enhance the learning experience.": "Готовность использовать новые методы и технологии для улучшения обучения.",
        "Ready to Join Us?": "Готовы присоединиться?", "Here's How to Get Started": "С чего начать", "Familiarize yourself with Secret Coder and the diverse range of courses we offer.": "Познакомьтесь с Secret Coder и нашим каталогом курсов.", "Craft a compelling application that showcases your passion, expertise, and proposed course offerings.": "Подготовьте заявку: расскажите о своём опыте, интересах и будущих курсах.", "Apply Now": "Подать заявку", "Join SecretCoder's Global Community of Expert Instructors": "Присоединяйтесь к международному сообществу преподавателей SecretCoder",
        "First Name": "Имя", "Last Name": "Фамилия", "Phone Number": "Номер телефона", "What is the highest degree ?": "Ваш уровень образования", "High School": "Среднее образование", "Undergraduate": "Незаконченное высшее", "Graduate": "Высшее образование", "Post-Graduate": "Послевузовское образование", "What subject would you like to teach?": "Какой предмет вы хотите преподавать?", "Technology": "Технологии", "Marketing": "Маркетинг", "Business": "Бизнес", "Education": "Образование", "Address": "Адрес",
        "I acknowledge and warrant the truthfulness of the information I submit, I also acknowledge that I have read, understand, and I agree with all Terms of service, and that I fully agree that all sales are final and that there are no refunds whatsoever.": "Подтверждаю достоверность предоставленных сведений, ознакомление и согласие с условиями использования, а также с тем, что покупки окончательны и возврат средств не предусмотрен.", "Close": "Закрыть", "Apply": "Отправить заявку", "Join Us in Transforming Lives Through Education!": "Помогайте менять жизни с помощью образования!", "At SecretCoder, we believe that education has the power to transform lives. Join us in creating a world where knowledge knows no bounds, and together, let's inspire, innovate, and educate!": "В SecretCoder мы верим, что образование меняет жизнь. Давайте вместе делать знания доступными, вдохновлять и обучать!",
        "Course": "Курс", "Start at the beginning by learning HTML basics — an important foundation for building and editing web pages.": "Начните с основ HTML — важной базы для создания и редактирования веб-страниц.", "Instructor Name": "Преподаватель", "- SecretCoder Instructor": "— Преподаватель SecretCoder", "SecretCoder Instructor": "Преподаватель SecretCoder", "About this Course": "О курсе",
        "Fun fact: all websites use HTML — even this one. It's a fundamental part of every web developer's toolkit. HTML provides the content that gives web pages structure, by using elements and tags, you can add text, images, videos, forms, and more. Learning HTML basics is an important first step in your web development journey and an essential skill for front- and back-end developers.": "Все сайты используют HTML — даже этот. Это основной инструмент веб-разработчика: элементы и теги задают структуру страницы и позволяют добавлять текст, изображения, видео и формы. Изучение HTML — первый шаг в веб-разработке и важный навык для фронтенд- и бэкенд-разработчиков.",
        "Skills you'll gain": "Чему вы научитесь", "Structure pages with HTML": "Создавать структуру страниц на HTML", "Present data with tables": "Представлять данные в таблицах", "Write cleaner HTML": "Писать аккуратный HTML-код", "Syllabus": "Программа курса", "Elements and Structure": "Элементы и структура", "Introduction to HTML": "Введение в HTML", "HTMl Document Standards": "Стандарты HTML-документа", "Tables": "Таблицы", "HTML Tables": "Таблицы HTML", "Forms": "Формы", "HTML Forms": "Формы HTML", "Form Validation": "Проверка форм", "Semantic HTML": "Семантический HTML", "About the Instructor": "О преподавателе", "Developer": "Разработчик", "4.87 Instructor rating": "4,87 — рейтинг преподавателя", "1,533 reviews": "1 533 отзыва", "20 Students": "20 учащихся", "29 courses": "29 курсов",
        "Curriculum Director at Codecademy and creative technologist. She has designed a range of Codecademy courses, including Learn HTML, Learn C#, Learn Alexa, and the beginner-friendly Learn How to Code.": "Руководитель учебных программ Codecademy и специалист по креативным технологиям. Разработала курсы по HTML, C#, Alexa и основам программирования для начинающих.",
        "Duration": "Длительность", "Lectures": "Уроки", "Enrolled": "Записались", "240 students": "240 учащихся", "Language": "Язык", "English": "Английский", "Skill Level": "Уровень подготовки", "Deadline": "Срок доступа", "Life Time": "Бессрочно", "Certificate": "Сертификат", "Yes": "Да", "Share this Course": "Поделиться курсом",
        "Page not found - SecretCoder": "Страница не найдена — SecretCoder", "Page not found": "Страница не найдена", "The page may have moved or the address may be incorrect.": "Страница могла переместиться, либо адрес указан неверно.", "Return home": "На главную",
        "Secret Coder : About Us": "Secret Coder — О нас", "Secret Coder : Contact": "Secret Coder — Контакты", "Secret Coder : Courses": "Secret Coder — Курсы", "Secret Coder : Online Courses": "Secret Coder — Онлайн-курсы", "Secret Coder : Instructor": "Secret Coder — Преподавателям", "Secret Coder : Login": "Secret Coder — Вход", "Secret Coder : Signup": "Secret Coder — Регистрация", "My Learning - SecretCoder": "Моё обучение — SecretCoder", "Track your enrolled SecretCoder courses and learning progress.": "Ваши курсы SecretCoder и прогресс обучения.",
        "You have signed out.": "Вы вышли из аккаунта.", "Password must contain at least 8 characters.": "Пароль должен содержать не менее 8 символов.", "Account created successfully.": "Аккаунт создан.", "Check your email to confirm the account.": "Проверьте почту для подтверждения аккаунта.", "An account with this email already exists.": "Аккаунт с этой почтой уже существует.", "Incorrect email or password.": "Неверная почта или пароль.", "Welcome back!": "С возвращением!", "Enter your account email. Password reset is available after Supabase setup.": "Введите почту аккаунта. Сброс пароля доступен после подключения Supabase.", "Enter your email first.": "Сначала введите почту.", "Password reset email sent.": "Письмо для сброса пароля отправлено.", "Please log in before enrolling.": "Войдите в аккаунт, чтобы записаться на курс.", "Course added to My Learning.": "Курс добавлен в «Моё обучение».", "Course completed — congratulations!": "Курс завершён — поздравляем!", "Progress saved.": "Прогресс сохранён.", "Message sent successfully.": "Сообщение отправлено.", "Message saved on this device. Connect Supabase to receive it online.": "Сообщение сохранено на этом устройстве. Подключите Supabase для отправки онлайн.", "Thanks for subscribing!": "Спасибо за подписку!", "Application submitted successfully.": "Заявка отправлена.",
        "Invalid login credentials": "Неверная почта или пароль.", "User already registered": "Пользователь уже зарегистрирован.", "Email not confirmed": "Электронная почта не подтверждена.", "Failed to fetch": "Не удалось подключиться к серверу. Проверьте соединение.", "Signup requires a valid password": "Для регистрации нужен корректный пароль."
    };
    let language = "en";
    try { language = localStorage.getItem("secretcoder_language") || (navigator.language.toLowerCase().startsWith("ru") ? "ru" : "en"); } catch (_) {}
    language = language === "ru" ? "ru" : "en";
    const originals = new WeakMap();
    const attributes = new WeakMap();
    const normalize = value => value.replace(/\s+/g, " ").trim();
    function translate(value, target = language) {
        if (target !== "ru") return value;
        const key = normalize(value);
        let result = dictionary[key];
        if (!result && /^\d+(?:\.\d+)? Hrs$/.test(key)) result = key.replace(" Hrs", " ч").replace(".", ",");
        if (!result && /^\d+(?:\.\d+)?L\+ Learners$/.test(key)) result = `${Number.parseFloat(key) * 100} тыс.+ учащихся`;
        if (!result && /^\d+ courses?$/.test(key)) {
            const n = Number.parseInt(key), last = n % 10, teen = n % 100;
            result = `${n} ${last === 1 && teen !== 11 ? "курс" : last >= 2 && last <= 4 && (teen < 12 || teen > 14) ? "курса" : "курсов"}`;
        }
        if (!result && /^\d+% complete$/.test(key)) result = key.replace("% complete", "% завершено");
        return result ? value.replace(key === value ? value : value.trim(), result) : value;
    }
    function excluded(element) {
        return element.closest("script, style, noscript, .language-switch, #learner-name, [data-logout], #app-toast-host, .navbar-brand, [data-learning-root]");
    }
    function apply(root = document) {
        const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
        let node;
        while ((node = walker.nextNode())) {
            if (!node.parentElement || excluded(node.parentElement)) continue;
            if (!originals.has(node)) originals.set(node, node.nodeValue);
            node.nodeValue = translate(originals.get(node));
        }
        root.querySelectorAll("[placeholder], [title], [aria-label], img[alt], meta[name='description']").forEach(element => {
            if (excluded(element)) return;
            let saved = attributes.get(element);
            if (!saved) { saved = {}; attributes.set(element, saved); }
            ["placeholder", "title", "aria-label", "alt", "content"].forEach(name => {
                if (!element.hasAttribute(name)) return;
                if (!(name in saved)) saved[name] = element.getAttribute(name);
                element.setAttribute(name, translate(saved[name]));
            });
        });
        document.documentElement.lang = language;
        document.querySelectorAll(".language-switch").forEach(select => { select.value = language; select.setAttribute("aria-label", language === "ru" ? "Язык интерфейса" : "Interface language"); });
        const logout = document.querySelector("[data-logout]");
        if (logout) logout.title = translate("Sign out");
        const count = document.getElementById("course-count");
        if (count?.dataset.count !== undefined) {
            const n = Number(count.dataset.count);
            count.textContent = translate(`${n} course${n === 1 ? "" : "s"}`);
        }
    }
    function originalText(element) {
        if (!element) return "";
        const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
        let text = "", node;
        while ((node = walker.nextNode())) text += originals.get(node) ?? node.nodeValue;
        return text;
    }
    function initialize() {
        document.querySelectorAll("#google_translate_element").forEach(element => element.closest("a")?.remove());
        const host = document.querySelector(".navbar-nav") || document.body;
        const select = document.createElement("select");
        select.className = "language-switch form-select form-select-sm";
        select.innerHTML = '<option value="en" lang="en">English</option><option value="ru" lang="ru">Русский</option>';
        select.value = language;
        select.addEventListener("change", () => {
            language = select.value;
            try { localStorage.setItem("secretcoder_language", language); } catch (_) {}
            apply();
            document.dispatchEvent(new Event("secretcoder:languagechange"));
            document.querySelectorAll("#app-toast-host .alert").forEach(item => { item.textContent = translate(item.dataset.message || item.textContent); });
        });
        host.appendChild(select);
        if (!document.querySelector('script[src="js/main.js"]')) apply();
    }
    window.SecretCoderI18n = { translate, apply, originalText, register: entries => Object.assign(dictionary, entries) };
    document.documentElement.lang = language;
    document.addEventListener("DOMContentLoaded", initialize);
})();
