-- Initial production schema for SecretCoder.
create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id text not null,
  course_title text not null,
  course_image text not null default 'img/course-1.jpg',
  progress integer not null default 0 check (progress between 0 and 100),
  enrolled_at timestamptz not null default now(),
  unique (user_id, course_id)
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 120),
  email text not null check (char_length(email) between 3 and 320),
  subject text not null check (char_length(subject) between 1 and 200),
  message text not null check (char_length(message) between 1 and 5000),
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique check (char_length(email) between 3 and 320),
  created_at timestamptz not null default now()
);

create table if not exists public.instructor_applications (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  address text not null,
  created_at timestamptz not null default now()
);

alter table public.enrollments enable row level security;
alter table public.contact_messages enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.instructor_applications enable row level security;

create policy "Users can view own enrollments" on public.enrollments for select to authenticated using ((select auth.uid()) = user_id);
create policy "Users can enroll themselves" on public.enrollments for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Users can update own progress" on public.enrollments for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "Anyone can send contact messages" on public.contact_messages for insert to anon, authenticated with check (true);
create policy "Anyone can subscribe" on public.newsletter_subscribers for insert to anon, authenticated with check (true);
create policy "Anyone can apply as instructor" on public.instructor_applications for insert to anon, authenticated with check (true);

grant select, insert, update on public.enrollments to authenticated;
grant insert on public.contact_messages to anon, authenticated;
grant insert on public.newsletter_subscribers to anon, authenticated;
grant insert on public.instructor_applications to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
